# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-12 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
    ]
